FROM node:21-alpine

WORKDIR /app

RUN apk update && apk add --no-cache supervisor

COPY ./etc/supervisord.conf /etc/supervisord.conf
COPY ./etc/supervisor.d /etc/supervisor.d

COPY ./src/package*.json .
COPY ./src/yarn.lock .

RUN yarn install

COPY ./src .

EXPOSE 8080

CMD ["sh", "-c", "/usr/bin/supervisord -c /etc/supervisord.conf"]
